/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Adiciona uma nova demanda devolucao
 */
export const demandaControllerAdicionarDemandaBodyPlacaMin = 7;

export const demandaControllerAdicionarDemandaBodyPlacaMax = 7;
export const demandaControllerAdicionarDemandaBodyCargaSegregadaDefault = false;export const demandaControllerAdicionarDemandaBodyRetornoPaleteDefault = false;export const demandaControllerAdicionarDemandaBodyQuantidadePaletesDefault = 0;

export const demandaControllerAdicionarDemandaBody = zod.object({
  "centerId": zod.string(),
  "placa": zod.string().min(demandaControllerAdicionarDemandaBodyPlacaMin).max(demandaControllerAdicionarDemandaBodyPlacaMax),
  "transportadora": zod.string().min(1),
  "motorista": zod.string(),
  "telefone": zod.string().optional(),
  "cargaSegregada": zod.boolean().optional(),
  "retornoPalete": zod.boolean().optional(),
  "quantidadePaletes": zod.number().optional(),
  "adicionadoPorId": zod.string()
})

