/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Liberar demanda armazem
 */
export const liberarDemandaArmazemParams = zod.object({
  "demandaId": zod.string()
})

/**
 * @summary Lista as demandas por data
 */
export const listarDemandasPorDataParams = zod.object({
  "data": zod.string(),
  "centerId": zod.string()
})

/**
 * @summary Obtém informações da viagem Ravex
 */
export const getInfoByViagemIdRavexParams = zod.object({
  "viagemId": zod.string()
})

export const getInfoByViagemIdRavexResponsePlacaMin = 7;

export const getInfoByViagemIdRavexResponsePlacaMax = 7;
export const getInfoByViagemIdRavexResponseNotasItemItensItemDescricaoRegExp = new RegExp('^(?!produto não encontrado$).*$');


export const getInfoByViagemIdRavexResponse = zod.object({
  "idViagem": zod.string(),
  "placa": zod.string().min(getInfoByViagemIdRavexResponsePlacaMin).max(getInfoByViagemIdRavexResponsePlacaMax),
  "motorista": zod.string(),
  "transportadora": zod.string(),
  "notas": zod.array(zod.object({
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "notaFiscal": zod.string(),
  "notaFiscalParcial": zod.string().nullish(),
  "motivoDevolucao": zod.string(),
  "descMotivoDevolucao": zod.string().nullable(),
  "operador": zod.string().nullish(),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string().regex(getInfoByViagemIdRavexResponseNotasItemItensItemDescricaoRegExp),
  "pesoLiquido": zod.number(),
  "quantidadeRavex": zod.number(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "fatorConversao": zod.number(),
  "unPorCaixa": zod.number(),
  "decimal": zod.number()
}))
}))
}).refine(
  // 2. A função de validação agora recebe o objeto inteiro da nota ('data')
  (data) => {
    // 3. A lógica de validação:
    // Se o tipo NÃO FOR 'DEVOLUCAO_PARCIAL', a validação passa para este campo.
    if (data.notas.some(nota => nota.tipo !== 'DEVOLUCAO_PARCIAL')) {
      return true; 
    }
    
    // Se o tipo FOR 'DEVOLUCAO_PARCIAL', o campo notaFiscalParcial
    // deve existir e não pode ser uma string vazia.
    return !!data.notas.some(nota => nota.notaFiscalParcial && nota.notaFiscalParcial.trim() !== '');
  },
  // 4. O objeto de configuração do erro:
  {
    // A mensagem a ser exibida se a validação falhar (retornar false)
    message: 'Nota Fiscal Parcial é obrigatória para devoluções parciais',
    path: ['notas', 'notaFiscalParcial'], 
  }
)

/**
 * @summary Adiciona uma nova demanda via Ravex
 */
export const adicionarNovaDemandaViaRavexParams = zod.object({
  "centerId": zod.string()
})

export const adicionarNovaDemandaViaRavexBodyPlacaMin = 7;

export const adicionarNovaDemandaViaRavexBodyPlacaMax = 7;
export const adicionarNovaDemandaViaRavexBodyNotasItemItensItemDescricaoRegExp = new RegExp('^(?!produto não encontrado$).*$');


export const adicionarNovaDemandaViaRavexBody = zod.object({
  "idViagem": zod.string(),
  "placa": zod.string().min(adicionarNovaDemandaViaRavexBodyPlacaMin).max(adicionarNovaDemandaViaRavexBodyPlacaMax),
  "motorista": zod.string(),
  "transportadora": zod.string(),
  "notas": zod.array(zod.object({
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "notaFiscal": zod.string(),
  "notaFiscalParcial": zod.string().nullish(),
  "motivoDevolucao": zod.string(),
  "descMotivoDevolucao": zod.string().nullable(),
  "operador": zod.string().nullish(),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string().regex(adicionarNovaDemandaViaRavexBodyNotasItemItensItemDescricaoRegExp),
  "pesoLiquido": zod.number(),
  "quantidadeRavex": zod.number(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "fatorConversao": zod.number(),
  "unPorCaixa": zod.number(),
  "decimal": zod.number()
}))
}))
}).refine(
  // 2. A função de validação agora recebe o objeto inteiro da nota ('data')
  (data) => {
    // 3. A lógica de validação:
    // Se o tipo NÃO FOR 'DEVOLUCAO_PARCIAL', a validação passa para este campo.
    if (data.notas.some(nota => nota.tipo !== 'DEVOLUCAO_PARCIAL')) {
      return true; 
    }
    
    // Se o tipo FOR 'DEVOLUCAO_PARCIAL', o campo notaFiscalParcial
    // deve existir e não pode ser uma string vazia.
    return !!data.notas.some(nota => nota.notaFiscalParcial && nota.notaFiscalParcial.trim() !== '');
  },
  // 4. O objeto de configuração do erro:
  {
    // A mensagem a ser exibida se a validação falhar (retornar false)
    message: 'Nota Fiscal Parcial é obrigatória para devoluções parciais',
    path: ['notas', 'notaFiscalParcial'], 
  }
)


export const adicionarNovaDemandaViaRavexResponse = zod.number()

