/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Cria um novo produto
 */
export const criarNovoProdutoBody = zod.object({
  "sku": zod.string(),
  "codEan": zod.string().optional(),
  "codDum": zod.string().optional(),
  "descricao": zod.string(),
  "shelf": zod.number(),
  "tipoPeso": zod.enum(['PVAR', 'PPAR']),
  "pesoLiquidoCaixa": zod.number(),
  "pesoLiquidoUnidade": zod.number(),
  "unPorCaixa": zod.number(),
  "caixaPorPallet": zod.number(),
  "segmento": zod.enum(['SECO', 'REFR']),
  "empresa": zod.enum(['ITB', 'LDB', 'DPA'])
})

/**
 * @summary Busca um produto
 */
export const buscarProdutoParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Atualiza um produto
 */
export const atualizarProdutoParams = zod.object({
  "id": zod.string()
})

export const atualizarProdutoBody = zod.object({
  "sku": zod.string(),
  "codEan": zod.string().optional(),
  "codDum": zod.string().optional(),
  "descricao": zod.string(),
  "shelf": zod.number(),
  "tipoPeso": zod.enum(['PVAR', 'PPAR']),
  "pesoLiquidoCaixa": zod.number(),
  "pesoLiquidoUnidade": zod.number(),
  "unPorCaixa": zod.number(),
  "caixaPorPallet": zod.number(),
  "segmento": zod.enum(['SECO', 'REFR']),
  "empresa": zod.enum(['ITB', 'LDB', 'DPA'])
})

/**
 * @summary Deleta um produto
 */
export const deletarProdutoParams = zod.object({
  "id": zod.string()
})

