/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Adiciona uma nova transportadora
 */
export const adicionarTransportadoraParams = zod.object({
  "centerId": zod.string()
})

/**
 * @summary Busca todas as transportadoras por centro
 */
export const buscarTransportadorasPorCentroParams = zod.object({
  "centerId": zod.string()
})

export const buscarTransportadorasPorCentroResponseItem = zod.object({
  "id": zod.number(),
  "nome": zod.string(),
  "centerId": zod.string()
})
export const buscarTransportadorasPorCentroResponse = zod.array(buscarTransportadorasPorCentroResponseItem)

/**
 * @summary Edita uma transportadora
 */
export const editarTransportadoraParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Deleta uma transportadora
 */
export const deletarTransportadoraParams = zod.object({
  "id": zod.string()
})

