/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType } from '../../../http/axios.http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const prometheusControllerIndex = (
    
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<null>(
      {url: `/metrics`, method: 'GET', signal
    },
      options);
    }
  

export const getPrometheusControllerIndexQueryKey = () => {
    return [`/metrics`] as const;
    }

    
export const getPrometheusControllerIndexQueryOptions = <TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrometheusControllerIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof prometheusControllerIndex>>> = ({ signal }) => prometheusControllerIndex(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrometheusControllerIndexQueryResult = NonNullable<Awaited<ReturnType<typeof prometheusControllerIndex>>>
export type PrometheusControllerIndexQueryError = ErrorType<unknown>


export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof prometheusControllerIndex>>,
          TError,
          Awaited<ReturnType<typeof prometheusControllerIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof prometheusControllerIndex>>,
          TError,
          Awaited<ReturnType<typeof prometheusControllerIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrometheusControllerIndexQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



