/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Cria uma nova regra
 */
export const createRuleBodyEnabledDefault = true;

export const createRuleBody = zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "centerId": zod.string(),
  "enabled": zod.boolean().default(createRuleBodyEnabledDefault),
  "conditions": zod.any(),
  "createdBy": zod.string()
})

/**
 * @summary Valida uma regra
 */
export const validateRuleParams = zod.object({
  "centerId": zod.string()
})

export const validateRuleResponse = zod.string()

