/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { AddContabilRavexDtoRequestItemEmpresa } from './addContabilRavexDtoRequestItemEmpresa';
import type { AddContabilRavexDtoRequestItemTipo } from './addContabilRavexDtoRequestItemTipo';
import type { AddContabilRavexDtoRequestItemDevolucaoItensItem } from './addContabilRavexDtoRequestItemDevolucaoItensItem';

export type AddContabilRavexDtoRequestItem = {
  empresa: AddContabilRavexDtoRequestItemEmpresa;
  devolucaoDemandaId: number;
  notaFiscal: string;
  motivoDevolucao: string;
  descMotivoDevolucao?: string;
  nfParcial?: string;
  tipo: AddContabilRavexDtoRequestItemTipo;
  devolucaoItens: AddContabilRavexDtoRequestItemDevolucaoItensItem[];
};
