/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export interface CriarNovoFuncionarioDto {
  /** ID do centro */
  centerId: string;
  /** ID do funcionário */
  id: string;
  /** Nome do funcionário */
  nome: string;
  /** Turno do funcionário */
  turno: string;
}
