/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export interface DemandaDtoRequest {
  /**
   * @minLength 7
   * @maxLength 7
   */
  placa: string;
  idTransportadora: string;
  motorista: string;
  telefone?: string;
  cargaSegregada?: boolean;
  retornoPalete?: boolean;
  quantidadePaletes?: number;
}
