/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { Error400DtoOutputIssuesItemPathItem } from './error400DtoOutputIssuesItemPathItem';

export type Error400DtoOutputIssuesItem = {
  code: string;
  path: Error400DtoOutputIssuesItemPathItem[];
  message: string;
};
