/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ResultadoConferenciaDtoRequestStatus } from './resultadoConferenciaDtoRequestStatus';
import type { ResultadoConferenciaDtoRequestNfsItem } from './resultadoConferenciaDtoRequestNfsItem';
import type { ResultadoConferenciaDtoRequestItensItem } from './resultadoConferenciaDtoRequestItensItem';

export interface ResultadoConferenciaDtoRequest {
  id: number;
  placa: string;
  transportadora: string;
  motorista: string;
  status: ResultadoConferenciaDtoRequestStatus;
  data: string;
  nfs: ResultadoConferenciaDtoRequestNfsItem[];
  temperaturaBau: number;
  temperaturaProduto: number;
  itens: ResultadoConferenciaDtoRequestItensItem[];
}
