/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type ResultadoConferenciaDtoRequestItensItem = {
  sku: string;
  descricao: string;
  lote: string;
  quantidadeCaixasContabil: number;
  quantidadeUnidadesContabil: number;
  quantidadeCaixasFisico: number;
  quantidadeUnidadesFisico: number;
  avariaCaixas: number;
  avariaUnidades: number;
};
