/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ReturnInfoGeralRavexNotasItemAnyOfItensItem } from './returnInfoGeralRavexNotasItemAnyOfItensItem';

/**
 * @nullable
 */
export type ReturnInfoGeralRavexNotasItemAnyOf = {
  tipo: 'DEVOLUCAO_PARCIAL';
  notaFiscal: string;
  motivoDevolucao: string;
  /** @nullable */
  descMotivoDevolucao: string | null;
  /** @nullable */
  operador?: string | null;
  itens: ReturnInfoGeralRavexNotasItemAnyOfItensItem[];
  notaFiscalParcial: string;
} | null;
