/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ReturnInfoGeralRavexNotasItemAnyOfThreeTipo } from './returnInfoGeralRavexNotasItemAnyOfThreeTipo';
import type { ReturnInfoGeralRavexNotasItemAnyOfThreeItensItem } from './returnInfoGeralRavexNotasItemAnyOfThreeItensItem';

/**
 * @nullable
 */
export type ReturnInfoGeralRavexNotasItemAnyOfThree = {
  tipo: ReturnInfoGeralRavexNotasItemAnyOfThreeTipo;
  notaFiscal: string;
  motivoDevolucao: string;
  /** @nullable */
  descMotivoDevolucao: string | null;
  /** @nullable */
  operador?: string | null;
  itens: ReturnInfoGeralRavexNotasItemAnyOfThreeItensItem[];
  /** @nullable */
  notaFiscalParcial?: string | null;
} | null;
